# fly.toml file generated for log-shipper-production 2021-05-24T22:46:08+02:00

app = "selleck-log-shipper-production"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  ORG = ""
  ACCESS_TOKEN = ""
  DATADOG_API_KEY = ""

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[metrics]
  port = 9598
  path = "/metrics"

[[services]]
  http_checks = []
  internal_port = 8686
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.tcp_checks]]
    grace_period = "3s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
